/*action types for coursework management, constants used to ensure consistency over action/reducers */

export const ADD_COURSEWORK_REQUEST = 'ADD_COURSEWORK_REQUEST';
export const ADD_COURSEWORK_SUCCESS = 'ADD_COURSEWORK_SUCCESS';
export const ADD_COURSEWORK_FAIL = 'ADD_COURSEWORK_FAIL';
export const ADD_COURSEWORK_RESET = 'ADD_COURSEWORK_RESET'

export const GET_CLASS_COURSEWORK_REQUEST = 'GET_CLASS_COURSEWORK_REQUEST';
export const GET_CLASS_COURSEWORK_SUCCESS = 'GET_CLASS_COURSEWORK_SUCCESS';
export const GET_CLASS_COURSEWORK_FAIL = 'GET_CLASS_COURSEWORK_FAIL';
export const GET_CLASS_COURSEWORK_RESET = 'GET_CLASS_COURSEWORK_RESET';

export const GET_COURSEWORK_BY_ID_FAIL = 'GET_COURSEWORK_BY_ID_FAIL';
export const GET_COURSEWORK_BY_ID_REQUEST = 'GET_COURSEWORK_BY_ID_REQUEST';
export const GET_COURSEWORK_BY_ID_SUCCESS = 'GET_COURSEWORK_BY_ID_SUCCESS';
export const GET_COURSEWORK_BY_ID_RESET = 'GET_COURSEWORK_BY_ID_RESET';

export const UPDATE_COURSEWORK_FAIL = 'UPDATE_COURSEWORK_FAIL';
export const UPDATE_COURSEWORK_SUCCESS = 'UPDATE_COURSEWORK_SUCCESS';
export const UPDATE_COURSEWORK_REQUEST = 'UPDATE_COURSEWORK_REQUEST';
export const UPDATE_COURSEWORK_RESET = 'UPDATE_COURSEWORK_RESET';

export const DELETE_COURSEWORK_FAIL = 'DELETE_COURSEWORK_FAIL';
export const DELETE_COURSEWORK_SUCCESS = 'DELETE_COURSEWORK_SUCCESS';
export const DELETE_COURSEWORK_REQUEST = 'DELETE_COURSEWORK_REQUEST';
export const DELETE_COURSEWORK_RESET = 'DELETE_COURSEWORK_RESET';

export const GET_COURSEWORK_MARKS_FAIL = 'GET_COURSEWORK_MARKS_FAIL';
export const GET_COURSEWORK_MARKS_REQUEST = 'GET_COURSEWORK_MARKS_REQUEST';
export const GET_COURSEWORK_MARKS_SUCCESS = 'GET_COURSEWORK_MARKS_SUCCESS';

export const GET_STUDENT_COURSEWORK_FAIL = 'GET_STUDENT_COURSEWORK_FAIL';
export const GET_STUDENT_COURSEWORK_REQUEST = 'GET_STUDENT_COURSEWORK_REQUEST';
export const GET_STUDENT_COURSEWORK_SUCCESS = 'GET_STUDENT_COURSEWORK_SUCCESS';
export const GET_STUDENT_COURSEWORK_RESET = 'GET_STUDENT_COURSEWORK_RESET'

export const UPDATE_COURSEWORK_MARKS_FAIL = 'UPDATE_COURSEWORK_MARKS_FAIL';
export const UPDATE_COURSEWORK_MARKS_REQUEST = 'UPDATE_COURSEWORK_MARKS_REQUEST';
export const UPDATE_COURSEWORK_MARKS_SUCCESS = 'UPDATE_COURSEWORK_MARKS_SUCCESS';
export const UPDATE_COURSEWORK_MARKS_RESET = 'UPDATE_COURSEWORK_MARKS_RESET';

export const BATCH_UPLOAD_MARKS_FAIL = 'BATCH_UPLOAD_MARKS_FAIL'
export const BATCH_UPLOAD_MARKS_SUCCESS = 'BATCH_UPLOAD_MARKS_SUCCESS'
export const BATCH_UPLOAD_MARKS_REQUEST = 'BATCH_UPLOAD_MARKS_REQUEST'
export const BATCH_UPLOAD_MARKS_CLEANUP = 'BATCH_UPLOAD_MARKS_CLEANUP'

export const EDIT_CW_RESET = 'EDIT_CW_RESET'