/*action types for taking lecture attendance, constants used to ensure consistency over action/reducers */

export const ADD_LECTURE_REQUEST = 'ADD_LECTURE_REQUEST';
export const ADD_LECTURE_SUCCESS = 'ADD_LECTURE_SUCCESS';
export const ADD_LECTURE_FAIL = 'ADD_LECTURE_FAIL';
export const ADD_LECTURE_RESET = 'ADD_LECTURE_RESET';

export const LOG_ATTENDANCE_REQUEST = 'LOG_ATTENDANCE_REQUEST';
export const LOG_ATTENDANCE_SUCCESS = 'LOG_ATTENDANCE_SUCCESS';
export const LOG_ATTENDANCE_FAIL = 'LOG_ATTENDANCE_FAIL';
export const LOG_ATTENDANCE_RESET = 'LOG_ATTENDANCE_RESET'

export const LOG_ATTENDANCE_EMAIL_REQUEST = 'LOG_ATTENDANCE_EMAIL_REQUEST';
export const LOG_ATTENDANCE_EMAIL_SUCCESS = 'LOG_ATTENDANCE_EMAIL_SUCCESS';
export const LOG_ATTENDANCE_EMAIL_FAIL = 'LOG_ATTENDANCE_EMAIL_FAIL';
export const LOG_ATTENDANCE_EMAIL_RESET = 'LOG_ATTENDANCE_EMAIL_RESET';

export const GET_LECTURE_ATTENDANCE_REQUEST = 'GET_LECTURE_ATTENDANCE_REQUEST';
export const GET_LECTURE_ATTENDANCE_SUCCESS = 'GET_LECTURE_ATTENDANCE_SUCCESS';
export const GET_LECTURE_ATTENDANCE_FAIL = 'GET_LECTURE_SUCCESS_FAIL';

export const DEFAULT_ATTENDANCE_REQUEST = 'DEFAULT_ATTENDANCE_REQUEST';

export const GET_LECTURE_SESSIONS_REQUEST = 'GET_LECTURE_SESSIONS_REQUEST';
export const GET_LECTURE_SESSIONS_SUCCESS = 'GET_LECTURE_SESSIONS_SUCCESS';
export const GET_LECTURE_SESSIONS_FAIL = 'GET_LECTURE_SESSIONS_FAIL'

export const GET_SUB_CLASSES_FAIL = 'GET_SUB_CLASSES_FAIL';
export const GET_SUB_CLASSES_REQUEST = 'GET_SUB_CLASSES_REQUEST';
export const GET_SUB_CLASSES_SUCCESS = 'GET_SUB_CLASSES_SUCESS'
export const GET_SUB_CLASSES_RESET = 'GET_SUB_CLASSES_RESET'

export const GET_SUB_REGISTER_FAIL = 'GET_SUB_REGISTER_FAIL';
export const GET_SUB_REGISTER_REQUEST = 'GET_SUB_REGISTER_REQUEST';
export const GET_SUB_REGISTER_SUCCESS = 'GET_SUB_REGISTER_SUCESS'
export const GET_SUB_REGISTER_RESET = 'GET_SUB_REGISTER_RESET'

export const ADD_SUB_FAIL = 'ADD_SUB_FAIL';
export const ADD_SUB_REQUEST = 'ADD_SUB_REQUEST';
export const ADD_SUB_SUCCESS = 'ADD_SUB_SUCESS'
export const ADD_SUB_RESET = 'ADD_SUB_RESET'

export const STUDENT_QR_ATTENDANCE_REQUEST = 'STUDENT_QR_ATTENDANCE_REQUEST';
export const STUDENT_QR_ATTENDANCE_SUCCESS = 'STUDENT_QR_ATTENDANCE_SUCCESS';
export const STUDENT_QR_ATTENDANCE_FAIL = 'STUDENT_QR_SUCCESS_FAIL';