/*action types for handling staff login, constants used to ensure consistency over action/reducers */

export const STAFF_LOGIN_REQUEST = 'STAFF_LOGIN_REQUEST';
export const STAFF_LOGIN_SUCCESS = 'STAFF_LOGIN_SUCCESS';
export const STAFF_LOGIN_FAIL = 'STAFF_LOGIN_FAIL';
export const STAFF_LOGOUT = 'STAFF_LOGOUT';

export const STAFF_CLASSES_REQUEST = 'STAFF_CLASSES_REQUEST';
export const STAFF_CLASSES_SUCCESS = 'STAFF_CLASSES_SUCCESS';
export const STAFF_CLASSES_FAIL = 'STAFF_CLASSES_FAIL';

export const STAFF_ADVISEES_REQUEST = 'STAFF_ADVISEES_REQUEST';
export const STAFF_ADVISEES_SUCCESS = 'STAFF_ADVISEES_SUCCESS';
export const STAFF_ADVISEES_FAIL = 'STAFF_ADVISEES_FAIL';

export const STAFF_NOTIFICATIONS_REQUEST = 'STAFF_NOTIFICATIONS_REQUEST';
export const STAFF_NOTIFICATIONS_SUCCESS = 'STAFF_NOTIFICATIONS_SUCCESS';
export const STAFF_NOTIFICATIONS_FAIL = 'STAFF_NOTIFICATIONS_FAIL';

export const STAFF_REGISTER_REQUEST = 'STAFF_REGISTER_REQUEST'