/*action types for handling student session, constants used to ensure consistency over action/reducers */

export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';

export const GET_STUDENT_CIRCUMSTANCES_REQUEST = 'GET_STUDENT_CIRCUMSTANCES_REQUEST';
export const GET_STUDENT_CIRCUMSTANCES_SUCCESS = 'GET_STUDENT_CIRCUMSTANCES_SUCCESS';
export const GET_STUDENT_CIRCUMSTANCES_FAIL = 'GET_STUDENT_CIRCUMSTANCES_FAIL';

export const SUBMIT_CIRCUMSTANCE_FAIL = 'SUBMIT_CIRCUMSTANCE_FAIL';
export const SUBMIT_CIRCUMSTANCE_SUCCESS = 'SUBMIT_CIRCUMSTANCE_SUCCESS';
export const SUBMIT_CIRCUMSTANCE_REQUEST = 'SUBMIT_CIRCUMSTANCE_REQUEST';
export const SUBMIT_CIRCUMSTANCE_RESET = 'SUBMIT_CIRCUMSTANCE_RESET';

export const STUDENT_CIRCUMSTANCE_SUBMISSIONS_REQUEST = 'STUDENT_CIRCUMSTANCE_SUBMISSIONS_REQUEST';
export const STUDENT_CIRCUMSTANCE_SUBMISSIONS_SUCCESS = 'STUDENT_CIRCUMSTANCE_SUBMISSIONS_SUCCESS';
export const STUDENT_CIRCUMSTANCE_SUBMISSIONS_FAIL = 'STUDENT_CIRCUMSTANCE_SUBMISSIONS_FAIL';

export const STUDENT_NOTIFICATIONS_REQUEST = 'STUDENT_NOTIFICATIONS_REQUEST';
export const STUDENT_NOTIFICATIONS_SUCCESS = 'STUDENT_NOTIFICATIONS_SUCCESS';
export const STUDENT_NOTIFICATIONS_FAIL = 'STUDENT_NOTIFICATIONS_FAIL';

export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST';