/*action types for fetching student data, constants used to ensure consistency over action/reducers */

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST';
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS';
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL';
export const STUDENT_DETAILS_CLEANUP = 'STUDENT_DETAILS_CLEANUP';

export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';

export const ADVISEE_LIST_FAIL = 'ADVISEE_LIST_FAIL';
export const ADVISEE_LIST_SUCCESS = 'ADVISEE_LIST_SUCCESS';
export const ADVISEE_LIST_REQUEST = 'ADVISEE_LIST_REQUEST';

export const STUDENT_DETAILED_PROFILE_FAIL = 'STUDENT_DETAILED_PROFILE_FAIL';
export const STUDENT_DETAILED_PROFILE_SUCCESS = 'STUDENT_DETAILED_PROFILE_SUCCESS';
export const STUDENT_DETAILED_PROFILE_REQUEST = 'STUDENT_DETAILED_PROFILE_REQUEST';

export const DEPARTMENT_STUDENTS_FAIL = 'DEPARTMENT_STUDENTS_FAIL';
export const DEPARTMENT_STUDENTS_SUCCESS = 'DEPARTMENT_STUDENTS_SUCCESS';
export const DEPARTMENT_STUDENTS_REQUEST = 'DEPARTMENT_STUDENTS_REQUEST';

export const CLASS_PDF_FAIL = 'CLASS_PDF_FAIL';
export const CLASS_PDF_SUCCESS = 'CLASS_PDF_SUCCESS';
export const CLASS_PDF_REQUEST = 'CLASS_PDF_REQUEST';

